/* eslint-disable prettier/prettier */

export { default as IconAdd } from './components/Add'
export { default as IconApps } from './components/Apps'
export { default as IconBlank } from './components/Blank'
export { default as IconCheck } from './components/Check'
export { default as IconCross } from './components/Cross'
export { default as IconFundraising } from './components/Fundraising'
export { default as IconGroups } from './components/Groups'
export { default as IconHome } from './components/Home'
export { default as IconIdentity } from './components/Identity'
export { default as IconNotifications } from './components/Notifications'
export { default as IconPermissions } from './components/Permissions'
export { default as IconSettings } from './components/Settings'
export { default as IconShare } from './components/Share'
export { default as IconTime } from './components/Time'
export { default as IconWallet } from './components/Wallet'
