// flow-typed signature: 49a84bbb6875eca2933e577433d413c3
// flow-typed version: <<STUB>>/opencolor_v^0.2.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opencolor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opencolor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'opencolor/lib/color_value' {
  declare module.exports: any;
}

declare module 'opencolor/lib/entry' {
  declare module.exports: any;
}

declare module 'opencolor/lib/index' {
  declare module.exports: any;
}

declare module 'opencolor/lib/meta_proxy' {
  declare module.exports: any;
}

declare module 'opencolor/lib/meta_value' {
  declare module.exports: any;
}

declare module 'opencolor/lib/parser_error' {
  declare module.exports: any;
}

declare module 'opencolor/lib/parser' {
  declare module.exports: any;
}

declare module 'opencolor/lib/reference' {
  declare module.exports: any;
}

declare module 'opencolor/lib/renderer' {
  declare module.exports: any;
}

declare module 'opencolor/src/color_value' {
  declare module.exports: any;
}

declare module 'opencolor/src/entry' {
  declare module.exports: any;
}

declare module 'opencolor/src/index' {
  declare module.exports: any;
}

declare module 'opencolor/src/meta_proxy' {
  declare module.exports: any;
}

declare module 'opencolor/src/meta_value' {
  declare module.exports: any;
}

declare module 'opencolor/src/parser_error' {
  declare module.exports: any;
}

declare module 'opencolor/src/parser' {
  declare module.exports: any;
}

declare module 'opencolor/src/reference' {
  declare module.exports: any;
}

declare module 'opencolor/src/renderer' {
  declare module.exports: any;
}

declare module 'opencolor/test/color_value_test' {
  declare module.exports: any;
}

declare module 'opencolor/test/entry_clone_test' {
  declare module.exports: any;
}

declare module 'opencolor/test/entry_manipulation_test' {
  declare module.exports: any;
}

declare module 'opencolor/test/entry_test' {
  declare module.exports: any;
}

declare module 'opencolor/test/error_reporting_test' {
  declare module.exports: any;
}

declare module 'opencolor/test/manual_creation_test' {
  declare module.exports: any;
}

declare module 'opencolor/test/metadata_parsing_test' {
  declare module.exports: any;
}

declare module 'opencolor/test/parser_test' {
  declare module.exports: any;
}

declare module 'opencolor/test/reference_parsing_test' {
  declare module.exports: any;
}

declare module 'opencolor/test/renderer_test' {
  declare module.exports: any;
}

declare module 'opencolor/test/traversal_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'opencolor/lib/color_value.js' {
  declare module.exports: $Exports<'opencolor/lib/color_value'>;
}
declare module 'opencolor/lib/entry.js' {
  declare module.exports: $Exports<'opencolor/lib/entry'>;
}
declare module 'opencolor/lib/index.js' {
  declare module.exports: $Exports<'opencolor/lib/index'>;
}
declare module 'opencolor/lib/meta_proxy.js' {
  declare module.exports: $Exports<'opencolor/lib/meta_proxy'>;
}
declare module 'opencolor/lib/meta_value.js' {
  declare module.exports: $Exports<'opencolor/lib/meta_value'>;
}
declare module 'opencolor/lib/parser_error.js' {
  declare module.exports: $Exports<'opencolor/lib/parser_error'>;
}
declare module 'opencolor/lib/parser.js' {
  declare module.exports: $Exports<'opencolor/lib/parser'>;
}
declare module 'opencolor/lib/reference.js' {
  declare module.exports: $Exports<'opencolor/lib/reference'>;
}
declare module 'opencolor/lib/renderer.js' {
  declare module.exports: $Exports<'opencolor/lib/renderer'>;
}
declare module 'opencolor/src/color_value.js' {
  declare module.exports: $Exports<'opencolor/src/color_value'>;
}
declare module 'opencolor/src/entry.js' {
  declare module.exports: $Exports<'opencolor/src/entry'>;
}
declare module 'opencolor/src/index.js' {
  declare module.exports: $Exports<'opencolor/src/index'>;
}
declare module 'opencolor/src/meta_proxy.js' {
  declare module.exports: $Exports<'opencolor/src/meta_proxy'>;
}
declare module 'opencolor/src/meta_value.js' {
  declare module.exports: $Exports<'opencolor/src/meta_value'>;
}
declare module 'opencolor/src/parser_error.js' {
  declare module.exports: $Exports<'opencolor/src/parser_error'>;
}
declare module 'opencolor/src/parser.js' {
  declare module.exports: $Exports<'opencolor/src/parser'>;
}
declare module 'opencolor/src/reference.js' {
  declare module.exports: $Exports<'opencolor/src/reference'>;
}
declare module 'opencolor/src/renderer.js' {
  declare module.exports: $Exports<'opencolor/src/renderer'>;
}
declare module 'opencolor/test/color_value_test.js' {
  declare module.exports: $Exports<'opencolor/test/color_value_test'>;
}
declare module 'opencolor/test/entry_clone_test.js' {
  declare module.exports: $Exports<'opencolor/test/entry_clone_test'>;
}
declare module 'opencolor/test/entry_manipulation_test.js' {
  declare module.exports: $Exports<'opencolor/test/entry_manipulation_test'>;
}
declare module 'opencolor/test/entry_test.js' {
  declare module.exports: $Exports<'opencolor/test/entry_test'>;
}
declare module 'opencolor/test/error_reporting_test.js' {
  declare module.exports: $Exports<'opencolor/test/error_reporting_test'>;
}
declare module 'opencolor/test/manual_creation_test.js' {
  declare module.exports: $Exports<'opencolor/test/manual_creation_test'>;
}
declare module 'opencolor/test/metadata_parsing_test.js' {
  declare module.exports: $Exports<'opencolor/test/metadata_parsing_test'>;
}
declare module 'opencolor/test/parser_test.js' {
  declare module.exports: $Exports<'opencolor/test/parser_test'>;
}
declare module 'opencolor/test/reference_parsing_test.js' {
  declare module.exports: $Exports<'opencolor/test/reference_parsing_test'>;
}
declare module 'opencolor/test/renderer_test.js' {
  declare module.exports: $Exports<'opencolor/test/renderer_test'>;
}
declare module 'opencolor/test/traversal_test.js' {
  declare module.exports: $Exports<'opencolor/test/traversal_test'>;
}
