// flow-typed signature: 9ad21eed55c19a96f599c87dfdc5534f
// flow-typed version: <<STUB>>/opencolor-converter_vgit://github.com/opencolor-tools/opencolor-converter.git#v2.1.21/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opencolor-converter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opencolor-converter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'opencolor-converter/examples/convert-examples' {
  declare module.exports: any;
}

declare module 'opencolor-converter/examples/export-examples' {
  declare module.exports: any;
}

declare module 'opencolor-converter/lib/aco' {
  declare module.exports: any;
}

declare module 'opencolor-converter/lib/css' {
  declare module.exports: any;
}

declare module 'opencolor-converter/lib/factory' {
  declare module.exports: any;
}

declare module 'opencolor-converter/lib/image' {
  declare module.exports: any;
}

declare module 'opencolor-converter/lib/index' {
  declare module.exports: any;
}

declare module 'opencolor-converter/lib/json' {
  declare module.exports: any;
}

declare module 'opencolor-converter/lib/less' {
  declare module.exports: any;
}

declare module 'opencolor-converter/lib/sass' {
  declare module.exports: any;
}

declare module 'opencolor-converter/lib/scss' {
  declare module.exports: any;
}

declare module 'opencolor-converter/lib/stylesheet' {
  declare module.exports: any;
}

declare module 'opencolor-converter/lib/swift' {
  declare module.exports: any;
}

declare module 'opencolor-converter/src/aco' {
  declare module.exports: any;
}

declare module 'opencolor-converter/src/css' {
  declare module.exports: any;
}

declare module 'opencolor-converter/src/factory' {
  declare module.exports: any;
}

declare module 'opencolor-converter/src/image' {
  declare module.exports: any;
}

declare module 'opencolor-converter/src/index' {
  declare module.exports: any;
}

declare module 'opencolor-converter/src/json' {
  declare module.exports: any;
}

declare module 'opencolor-converter/src/less' {
  declare module.exports: any;
}

declare module 'opencolor-converter/src/scss' {
  declare module.exports: any;
}

declare module 'opencolor-converter/src/stylesheet' {
  declare module.exports: any;
}

declare module 'opencolor-converter/src/swift' {
  declare module.exports: any;
}

declare module 'opencolor-converter/test/aco' {
  declare module.exports: any;
}

declare module 'opencolor-converter/test/css' {
  declare module.exports: any;
}

declare module 'opencolor-converter/test/image' {
  declare module.exports: any;
}

declare module 'opencolor-converter/test/json' {
  declare module.exports: any;
}

declare module 'opencolor-converter/test/less' {
  declare module.exports: any;
}

declare module 'opencolor-converter/test/lib' {
  declare module.exports: any;
}

declare module 'opencolor-converter/test/scss' {
  declare module.exports: any;
}

declare module 'opencolor-converter/test/swift' {
  declare module.exports: any;
}

// Filename aliases
declare module 'opencolor-converter/examples/convert-examples.js' {
  declare module.exports: $Exports<'opencolor-converter/examples/convert-examples'>;
}
declare module 'opencolor-converter/examples/export-examples.js' {
  declare module.exports: $Exports<'opencolor-converter/examples/export-examples'>;
}
declare module 'opencolor-converter/lib/aco.js' {
  declare module.exports: $Exports<'opencolor-converter/lib/aco'>;
}
declare module 'opencolor-converter/lib/css.js' {
  declare module.exports: $Exports<'opencolor-converter/lib/css'>;
}
declare module 'opencolor-converter/lib/factory.js' {
  declare module.exports: $Exports<'opencolor-converter/lib/factory'>;
}
declare module 'opencolor-converter/lib/image.js' {
  declare module.exports: $Exports<'opencolor-converter/lib/image'>;
}
declare module 'opencolor-converter/lib/index.js' {
  declare module.exports: $Exports<'opencolor-converter/lib/index'>;
}
declare module 'opencolor-converter/lib/json.js' {
  declare module.exports: $Exports<'opencolor-converter/lib/json'>;
}
declare module 'opencolor-converter/lib/less.js' {
  declare module.exports: $Exports<'opencolor-converter/lib/less'>;
}
declare module 'opencolor-converter/lib/sass.js' {
  declare module.exports: $Exports<'opencolor-converter/lib/sass'>;
}
declare module 'opencolor-converter/lib/scss.js' {
  declare module.exports: $Exports<'opencolor-converter/lib/scss'>;
}
declare module 'opencolor-converter/lib/stylesheet.js' {
  declare module.exports: $Exports<'opencolor-converter/lib/stylesheet'>;
}
declare module 'opencolor-converter/lib/swift.js' {
  declare module.exports: $Exports<'opencolor-converter/lib/swift'>;
}
declare module 'opencolor-converter/src/aco.js' {
  declare module.exports: $Exports<'opencolor-converter/src/aco'>;
}
declare module 'opencolor-converter/src/css.js' {
  declare module.exports: $Exports<'opencolor-converter/src/css'>;
}
declare module 'opencolor-converter/src/factory.js' {
  declare module.exports: $Exports<'opencolor-converter/src/factory'>;
}
declare module 'opencolor-converter/src/image.js' {
  declare module.exports: $Exports<'opencolor-converter/src/image'>;
}
declare module 'opencolor-converter/src/index.js' {
  declare module.exports: $Exports<'opencolor-converter/src/index'>;
}
declare module 'opencolor-converter/src/json.js' {
  declare module.exports: $Exports<'opencolor-converter/src/json'>;
}
declare module 'opencolor-converter/src/less.js' {
  declare module.exports: $Exports<'opencolor-converter/src/less'>;
}
declare module 'opencolor-converter/src/scss.js' {
  declare module.exports: $Exports<'opencolor-converter/src/scss'>;
}
declare module 'opencolor-converter/src/stylesheet.js' {
  declare module.exports: $Exports<'opencolor-converter/src/stylesheet'>;
}
declare module 'opencolor-converter/src/swift.js' {
  declare module.exports: $Exports<'opencolor-converter/src/swift'>;
}
declare module 'opencolor-converter/test/aco.js' {
  declare module.exports: $Exports<'opencolor-converter/test/aco'>;
}
declare module 'opencolor-converter/test/css.js' {
  declare module.exports: $Exports<'opencolor-converter/test/css'>;
}
declare module 'opencolor-converter/test/image.js' {
  declare module.exports: $Exports<'opencolor-converter/test/image'>;
}
declare module 'opencolor-converter/test/json.js' {
  declare module.exports: $Exports<'opencolor-converter/test/json'>;
}
declare module 'opencolor-converter/test/less.js' {
  declare module.exports: $Exports<'opencolor-converter/test/less'>;
}
declare module 'opencolor-converter/test/lib.js' {
  declare module.exports: $Exports<'opencolor-converter/test/lib'>;
}
declare module 'opencolor-converter/test/scss.js' {
  declare module.exports: $Exports<'opencolor-converter/test/scss'>;
}
declare module 'opencolor-converter/test/swift.js' {
  declare module.exports: $Exports<'opencolor-converter/test/swift'>;
}
