// flow-typed signature: 46a02f9f836a77aa6aa47b85e8a379d7
// flow-typed version: <<STUB>>/react-onclickout_v^2.0.8/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-onclickout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-onclickout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-onclickout/src/index' {
  declare module.exports: any;
}

declare module 'react-onclickout/test/compiler' {
  declare module.exports: any;
}

declare module 'react-onclickout/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-onclickout/index' {
  declare module.exports: $Exports<'react-onclickout'>;
}
declare module 'react-onclickout/index.js' {
  declare module.exports: $Exports<'react-onclickout'>;
}
declare module 'react-onclickout/src/index.jsx' {
  declare module.exports: $Exports<'react-onclickout/src/index'>;
}
declare module 'react-onclickout/test/compiler.js' {
  declare module.exports: $Exports<'react-onclickout/test/compiler'>;
}
declare module 'react-onclickout/test/index.jsx' {
  declare module.exports: $Exports<'react-onclickout/test/index'>;
}
