// flow-typed signature: f0f9eb4ff0cf30318002ad28e672e36f
// flow-typed version: <<STUB>>/rollup-plugin-url_v^1.3.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-url/dist/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-url/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-url/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-url/dist/index'>;
}
declare module 'rollup-plugin-url/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-url/src/index'>;
}
