// flow-typed signature: b1e17863d159f6b2bf094d6251bcd46f
// flow-typed version: <<STUB>>/rollup-plugin-rebase_v^0.12.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-rebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-rebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-rebase/__tests__/fixtures/assets' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/__tests__/fixtures/deep/assets-mixed' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/__tests__/fixtures/deep/assets-outside' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/__tests__/fixtures/plain' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/__tests__/fixtures/script' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/__tests__/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/__tests__/output/assets-hash-appened/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/__tests__/output/assets/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/__tests__/output/mixed/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/__tests__/output/outside/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/__tests__/output/plain/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/gulpfile' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/lib/node.commonjs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/lib/node.es2015' {
  declare module.exports: any;
}

declare module 'rollup-plugin-rebase/lib/node.esmodule' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-rebase/__tests__/fixtures/assets.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/__tests__/fixtures/assets'>;
}
declare module 'rollup-plugin-rebase/__tests__/fixtures/deep/assets-mixed.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/__tests__/fixtures/deep/assets-mixed'>;
}
declare module 'rollup-plugin-rebase/__tests__/fixtures/deep/assets-outside.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/__tests__/fixtures/deep/assets-outside'>;
}
declare module 'rollup-plugin-rebase/__tests__/fixtures/plain.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/__tests__/fixtures/plain'>;
}
declare module 'rollup-plugin-rebase/__tests__/fixtures/script.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/__tests__/fixtures/script'>;
}
declare module 'rollup-plugin-rebase/__tests__/index.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/__tests__/index'>;
}
declare module 'rollup-plugin-rebase/__tests__/output/assets-hash-appened/index.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/__tests__/output/assets-hash-appened/index'>;
}
declare module 'rollup-plugin-rebase/__tests__/output/assets/index.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/__tests__/output/assets/index'>;
}
declare module 'rollup-plugin-rebase/__tests__/output/mixed/index.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/__tests__/output/mixed/index'>;
}
declare module 'rollup-plugin-rebase/__tests__/output/outside/index.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/__tests__/output/outside/index'>;
}
declare module 'rollup-plugin-rebase/__tests__/output/plain/index.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/__tests__/output/plain/index'>;
}
declare module 'rollup-plugin-rebase/gulpfile.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/gulpfile'>;
}
declare module 'rollup-plugin-rebase/lib/node.commonjs.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/lib/node.commonjs'>;
}
declare module 'rollup-plugin-rebase/lib/node.es2015.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/lib/node.es2015'>;
}
declare module 'rollup-plugin-rebase/lib/node.esmodule.js' {
  declare module.exports: $Exports<'rollup-plugin-rebase/lib/node.esmodule'>;
}
