// flow-typed signature: ba157ea8ea616e79617a6e1556e8794c
// flow-typed version: <<STUB>>/svgr_v^1.1.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svgr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svgr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svgr/lib/__fixtures__/dist/main' {
  declare module.exports: any;
}

declare module 'svgr/lib/__fixtures__/main' {
  declare module.exports: any;
}

declare module 'svgr/lib/cli/dirCommand' {
  declare module.exports: any;
}

declare module 'svgr/lib/cli/fileCommand' {
  declare module.exports: any;
}

declare module 'svgr/lib/cli/index' {
  declare module.exports: any;
}

declare module 'svgr/lib/cli/util' {
  declare module.exports: any;
}

declare module 'svgr/lib/configToOptions' {
  declare module.exports: any;
}

declare module 'svgr/lib/h2x/emSize' {
  declare module.exports: any;
}

declare module 'svgr/lib/h2x/expandProps' {
  declare module.exports: any;
}

declare module 'svgr/lib/h2x/removeComments' {
  declare module.exports: any;
}

declare module 'svgr/lib/h2x/removeStyle' {
  declare module.exports: any;
}

declare module 'svgr/lib/h2x/replaceAttrValue' {
  declare module.exports: any;
}

declare module 'svgr/lib/h2x/stripAttribute' {
  declare module.exports: any;
}

declare module 'svgr/lib/index' {
  declare module.exports: any;
}

declare module 'svgr/lib/plugins/h2x' {
  declare module.exports: any;
}

declare module 'svgr/lib/plugins/prettier' {
  declare module.exports: any;
}

declare module 'svgr/lib/plugins/svgo' {
  declare module.exports: any;
}

declare module 'svgr/lib/plugins/transform' {
  declare module.exports: any;
}

declare module 'svgr/lib/transforms/rename' {
  declare module.exports: any;
}

declare module 'svgr/lib/transforms/wrapIntoComponent' {
  declare module.exports: any;
}

declare module 'svgr/lib/webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svgr/lib/__fixtures__/dist/main.js' {
  declare module.exports: $Exports<'svgr/lib/__fixtures__/dist/main'>;
}
declare module 'svgr/lib/__fixtures__/main.js' {
  declare module.exports: $Exports<'svgr/lib/__fixtures__/main'>;
}
declare module 'svgr/lib/cli/dirCommand.js' {
  declare module.exports: $Exports<'svgr/lib/cli/dirCommand'>;
}
declare module 'svgr/lib/cli/fileCommand.js' {
  declare module.exports: $Exports<'svgr/lib/cli/fileCommand'>;
}
declare module 'svgr/lib/cli/index.js' {
  declare module.exports: $Exports<'svgr/lib/cli/index'>;
}
declare module 'svgr/lib/cli/util.js' {
  declare module.exports: $Exports<'svgr/lib/cli/util'>;
}
declare module 'svgr/lib/configToOptions.js' {
  declare module.exports: $Exports<'svgr/lib/configToOptions'>;
}
declare module 'svgr/lib/h2x/emSize.js' {
  declare module.exports: $Exports<'svgr/lib/h2x/emSize'>;
}
declare module 'svgr/lib/h2x/expandProps.js' {
  declare module.exports: $Exports<'svgr/lib/h2x/expandProps'>;
}
declare module 'svgr/lib/h2x/removeComments.js' {
  declare module.exports: $Exports<'svgr/lib/h2x/removeComments'>;
}
declare module 'svgr/lib/h2x/removeStyle.js' {
  declare module.exports: $Exports<'svgr/lib/h2x/removeStyle'>;
}
declare module 'svgr/lib/h2x/replaceAttrValue.js' {
  declare module.exports: $Exports<'svgr/lib/h2x/replaceAttrValue'>;
}
declare module 'svgr/lib/h2x/stripAttribute.js' {
  declare module.exports: $Exports<'svgr/lib/h2x/stripAttribute'>;
}
declare module 'svgr/lib/index.js' {
  declare module.exports: $Exports<'svgr/lib/index'>;
}
declare module 'svgr/lib/plugins/h2x.js' {
  declare module.exports: $Exports<'svgr/lib/plugins/h2x'>;
}
declare module 'svgr/lib/plugins/prettier.js' {
  declare module.exports: $Exports<'svgr/lib/plugins/prettier'>;
}
declare module 'svgr/lib/plugins/svgo.js' {
  declare module.exports: $Exports<'svgr/lib/plugins/svgo'>;
}
declare module 'svgr/lib/plugins/transform.js' {
  declare module.exports: $Exports<'svgr/lib/plugins/transform'>;
}
declare module 'svgr/lib/transforms/rename.js' {
  declare module.exports: $Exports<'svgr/lib/transforms/rename'>;
}
declare module 'svgr/lib/transforms/wrapIntoComponent.js' {
  declare module.exports: $Exports<'svgr/lib/transforms/wrapIntoComponent'>;
}
declare module 'svgr/lib/webpack.js' {
  declare module.exports: $Exports<'svgr/lib/webpack'>;
}
