const [fs, path] = [require('fs'), require('path')]

console.log(
  `// This file has been generated by running scripts/apps-index.js.
// Do not edit: manual changes will be overwritten.`
)
console.log(
  fs
    .readdirSync(__dirname + '/../apps')
    .filter(f => f !== 'index.js' && /\.js$/.test(f))
    .map(f => path.basename(f, '.js'))
    .map(f => `export { default as ${f} } from './${f}'`)
    .join('\n')
)
