export { default as UIBaseStyles } from './comps/BaseStyles/BaseStyles.vue'
export { default as UIButton } from './comps/Button/Button.vue'
export { default as UIFooter } from './comps/Footer/Footer.vue'
export { default as UIHeader } from './comps/Header/Header.vue'
export { default as UIIllustratedSection } from './comps/IllustratedSection/IllustratedSection.vue'
export { default as UIPreFooter } from './comps/PreFooter/PreFooter.vue'
export { default as UISection } from './comps/Section/Section.vue'
export { default as UIText } from './comps/Text/Text.vue'
